/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package auction.sniper;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.SwingUtilities;

import auction.sniper.adapters.xmpp.XMPPAuctionHouse;
import auction.sniper.core.AuctionHouse;
import auction.sniper.core.SniperLauncher;
import auction.sniper.core.SniperPortfolio;
import auction.sniper.ui.MainWindow;

public class App {

	private static final int ARG_HOSTNAME = 0;
	private static final int ARG_USERNAME = 1;
	private static final int ARG_PASSWORD = 2;

	public static final String MAIN_WINDOW_NAME = "Auction Sniper App";

	private final SniperPortfolio sniperPortfolio = new SniperPortfolio();

	private MainWindow ui;

	App() throws Exception {
		startUserInterface();
	}

	public static void main(String... args) throws Exception {
		final var app = new App();
		final var auctionHouse = XMPPAuctionHouse.connect(args[ARG_HOSTNAME], args[ARG_USERNAME], args[ARG_PASSWORD]);
		app.disconnectWhenUICloses(auctionHouse);
		app.addUserRequestListenerFor(auctionHouse);
	}

	private void addUserRequestListenerFor(final AuctionHouse auctionHouse) {
		ui.addUserRequestListener(new SniperLauncher(auctionHouse, sniperPortfolio));
	}

	private void disconnectWhenUICloses(final XMPPAuctionHouse auctionHouse) {
		ui.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosed(WindowEvent e) {
				auctionHouse.disconnect();
			}
		});
	}

	private void startUserInterface() throws Exception {
		SwingUtilities.invokeAndWait(() -> ui = new MainWindow(sniperPortfolio));
	}
}
